name: Build, Push to ECR, and Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials for ECR and EC2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to Amazon ECR Public (login to AWS ECR for pushing/pulling images)
      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j4n7l1s4

      # 4. Build, tag, and push Docker image to ECR
      - name: Build, tag, and push Docker image
        run: |
          # Build Docker image from the ./mediplus directory
          docker build -t mediplus-ecr:v2 .   # Path adjusted as per your repo structure

          # Tag the image for ECR
          docker tag mediplus-ecr:v2 public.ecr.aws/j4n7l1s4/mediplus-ecr:v2

          # Push the image to ECR
          docker push public.ecr.aws/j4n7l1s4/mediplus-ecr:v2 

  deploy:
    runs-on: ubuntu-latest
    needs: build-push

  steps:
    - name: check my EC2_SSH_KEY
      run: |
          echo '${{ secrets.EC2_SSH_KEY }}' > workflow-cicd.pem
          chmod 600 workflow-cicd.pem

    - name: Authenticate to AWS ECR, pull and run the image
     run: |          
        ssh -o StrictHostKeyChecking=no -i workflow-cicd.pem ubuntu@54.175.106.147 'docker pull public.ecr.aws/j4n7l1s4/mediplus-ecr:v2

        ssh -o StrictHostKeyChecking=no -i workflow-cicd.pem ubuntu@54.175.106.147 'docker run -d -p 8081:80 --name mediplus public.ecr.aws/j4n7l1s4/mediplus-ecr:v2'
#      ssh -o StrictHostKeyChecking=no -i workflow-cicd.pem ubuntu@172.31.81.66 'hostnamectl'


















































































































