name: Build, Push to ECR, and Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials for ECR and EC2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to Amazon ECR (login to AWS ECR for pushing/pulling images)
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin 062266257890.dkr.ecr.us-east-1.amazonaws.com

      # 4. Build, tag, and push Docker image to ECR
      - name: Build, tag, and push Docker image
        run: |
          set -x
          IMAGE_URI=062266257890.dkr.ecr.us-east-1.amazonaws.com/mediplus:latest  # Ensure the image tag matches your needs

          # Build Docker image from the root directory (assuming Dockerfile is in the repo's root)
          docker build -t mediplus .

          # Tag the image for ECR
          docker tag mediplus:latest $IMAGE_URI

          # Push the image to ECR
          docker push $IMAGE_URI

      # 5. Deploy Docker image to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}     # EC2 instance IP or DNS
          username: ${{ secrets.EC2_USER }}  # EC2 username (usually 'ubuntu' for Ubuntu instances)
          key: ${{ secrets.EC2_SSH_KEY }}    # Private SSH key stored as GitHub secret
          script: |
            set -x
            IMAGE_URI=062266257890.dkr.ecr.us-east-1.amazonaws.com/mediplus:latest  # Image URI used in EC2

            # Stop and remove any existing container (if running)
            sudo docker stop mediplus || true
            sudo docker rm mediplus || true

            # Log in to ECR from EC2 instance
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | sudo docker login --username AWS --password-stdin 062266257890.dkr.ecr.us-east-1.amazonaws.com

            # Pull the latest Docker image from ECR
            sudo docker pull $IMAGE_URI

            # Run the new container in detached mode, exposing port 80
            sudo docker run -d --name mediplus -p 80:80 $IMAGE_URI



























































































































