name: Build, Push to ECR, and Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials for ECR and EC2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to Amazon ECR Public (login to AWS ECR for pushing/pulling images)
      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j4n7l1s4

      # 4. Build, tag, and push Docker image to ECR
      - name: Build, tag, and push Docker image
        run: |
          # Build Docker image from the ./mediplus directory
          docker build -t mediplus-ecr:v2 .   # Path adjusted as per your repo structure

          # Tag the image for ECR
          docker tag mediplus-ecr:v2 public.ecr.aws/j4n7l1s4/mediplus-ecr:v2

          # Push the image to ECR
          docker push public.ecr.aws/j4n7l1s4/mediplus-ecr:v2 

      # 5. Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}     # Usually 'ubuntu'
          key: ${{ secrets.EC2_SSH_KEY }}       # Private SSH key stored as secret
          script: |
            IMAGE_URI=public.ecr.aws/j4n7l1s4/mediplus-ecr:v2

            # Stop and remove existing container
            sudo docker stop mediplus-ecr:v2 || true
            sudo docker rm mediplus-ecr:v2 || true

            # Log in to ECR
            aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin public.ecr.aws/j4n7l1s4

            # Pull the latest image version
            sudo docker pull $IMAGE_URI

            # Run new container
            sudo docker run -d --name mediplus-ecr:v2 -p 80:80 $IMAGE_URI


















































































































